name: "Dockle image linting and notify slack"
description: "Lints using Dockle and sends notification to Slack"
inputs:
  registry:
    description: "Registry's host"
    required: false
    default: "ghcr.io"
  user:
    description: "Registry's user"
    required: false
    default: ${{ github.actor }}
  password:
    description: "Registry user's password or token"
    required: true
  image:
    description: "Docker image name with tag"
    required: true
  slack-webhook:
    description: "Slack Webhook for notifications"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    
    # ==== DOCKLE LINTING ====
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.user }}
        password: ${{ inputs.password }}

    - name: Dockle Security Check
      uses: erzz/dockle-action@v1
      with:
        image: ${{ inputs.image }}
        failure-threshold: fatal
        exit-code: 1 # Stops pipeline if fatal issues found

    # ==== SLACK NOTIFICATION ====
    - name: Dockle Slack Notification
      uses: rtCamp/action-slack-notify@v2
      if: ${{ failure() }}
      env:
        SLACK_CHANNEL: dev
        SLACK_COLOR: danger
        SLACK_MESSAGE: |
          Dockle lint action check on *${{ github.ref_name }}* has failed for ${{ github.repository }}
        SLACK_TITLE: Deployment Failed
        SLACK_USERNAME: github-actions-status
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        SLACK_ICON: https://github.com/GETProtocolLab.png?size=48
